app/cdhlab/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('proses.urls')),

]

app/proses/urls.py
from django.urls import path

from . import views
from django.contrib.flatpages import views as fp_views

app_name = 'proses'

"""
    path('', views.IndexView.as_view(), name='index'),
"""

urlpatterns = [
    path('', views.index, name='index'),

    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path(r'import/', views.import_sheet, name='import'),
    path(r'explicits/', views.prose_table, name='explicit'),
    path(r'incipits/', views.prose_table, name='incipit'),
    path(r'subjects/', views.prose_table, name='subject'),
    path(r'titles/', views.prose_table, name='title'),
    path(r'volumes/', views.volume_index, name='volumes'),
    # path(r'book/', views.view_book, name='book'),

    path(r'search/', views.search),
    # path(r'volumes/', fp_views.flatpage, {'url':'/volumes/'}, name='volumes'),
    path(r'about/', fp_views.flatpage, {'url':'/about/'}, name='about'),


]

app/proses/models.py
from django.db import models
import re
import logging

# pattern = re.compile(r'(.*)[\/ \.]([0-9]+) [. ]*[\[\]0-9\-–]*\[[A-Z ]*([0-9]+)\] *$')
pattern = re.compile(r'(\w+) (.+) (\[+[A-Za-z0-9-\[\][]*[ -]* *[0-9]+\]+)')

book_vol_lookup = {
    "Amp": 6,
    "Ashmole": 9,
    "BC": 6,
    "Bham": 15,
    "BL": 5,
    "BMaz": 7,
    "BN": 7,
    "BodL": 12,
    "Brogyntyn": 14,
    "BSteG": 7,
    "Caius": 17,
    "CCCC": 20,
    "CFM": 18,
    "Chetham's": 2,
    "Cph": 10,
    "CUL": 19,
    "Digby": 3,
    "Douce": 4,
    "EL": 1,
    "Fitz": 18,
    "Glo": 15,
    "Hfd": 15,
    "HM": 1,
    "HU": 1,
    "Huseby": 10,
    "Lambeth": 13,
    "Laud": 16,
    "LD": 6,
    "Lei": 15,
    "Lich": 15,
    "Llanstephan" : 14,
    "McC": 18,
    "NLW": 14,
    "Not": 15,
    "NY": 6,
    "Oxf": 8,
    "Pem": 18,
    "Peniarth": 14,
    "Ptb": 15,
    "RCDCA": 6,
    "Ripon": 6,
    "Rylands": 2,
    "Schøyen": 10,
    "Shf": 6,
    "Sion": 13,
    "Sotheby": 14,
    "Stockh": 10,
    "Swl": 15,
    "Trefeglwys": 14,
    "Trinity": 11,
    "Uppsala": 10,
    "Wor": 15,
    "York": 6,
    "e": 21,
    "Hatton": 21,
    "Sidney": 22,
    "TrinHall": 22,
    "Christ's": 22,
    "P'house": 22,
    "Emma": 22,
    "Jesus": 22,
    "Selwyn": 22,
    "Rawl": 23
}


def get_book_from_name(input_name=''):
    name = str.strip(input_name)
    if name.__len__() > 0:
        '''ignore pattern, just split on first space '''
        bk_sort_text = name.split(' ')[0]
        imep_vol = book_vol_lookup.get(bk_sort_text)
        if not imep_vol:
            imep_vol = 999
        return Book.objects.get_or_create(book_name=input_name,
                                          book_sort_text=bk_sort_text.lower(),
                                          # book_num=bk_num,
                                          book_vol=imep_vol)


# Create your models here.
class Book(models.Model):
    def __str__(self):
        return self.book_name

    book_name = models.CharField(max_length=255, default='')
    book_sort_text = models.CharField(max_length=255, default='')
    # book_num = models.IntegerField(default=0)
    book_vol = models.IntegerField(default=0)

    class Meta:
        ordering=('book_sort_text', 'book_name', 'book_vol')


class Prose(models.Model):
    # ...
    def __str__(self):
        return self.prose_text

    def get_absolute_url(self):
        return '/proses/%i/' % self.id

    prose_text = models.CharField(max_length=500)
    prose_text_sort = models.CharField(max_length=500)
    type = models.CharField(max_length=20, default='explicits')
    printed = models.BooleanField(default=False)

    class Meta:
        ordering = ['prose_text_sort', ]


class ProseBook(models.Model):
    def __str__(self):
        return self.prose.prose_text + ' ' + self.book.book_name + ' ' + str(self.volume)

    prose = models.ForeignKey(Prose, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    volume = models.IntegerField(default=0)

    class Meta:
        ordering = ['prose__prose_text_sort', 'book__book_sort_text', 'book__book_name' ]

app/proses/forms.py
from django import forms


class ImportExcelForm(forms.Form):
    file = forms.FileField(label="Choose excel to upload")

app/proses/views.py
from urllib.parse import quote
from django import forms
from django.http import HttpResponseBadRequest, HttpResponse
from django.shortcuts import render
from django.views import generic
from django_tables2 import RequestConfig
from django.db.models import Q

import requests

from .import_file import *
from .tables import *

UPLOAD_TYPES = [
    ('explicit', 'Explicits, Books and Volumes'),
    ('incipit', 'Incipits, Books and Volumes'),
    ('subject', 'General Index'),
    ('title', 'Titles, Rubrics and Colophons'),

]

VIEW_TYPES = {'explicit': 'Reverse Explicits',
              'incipit': 'Incipits',
              'subject': 'General Index',
              'title': 'Titles, Rubrics and Colophons',
              }


def index(request):
    num_explicits = Prose.objects.filter(type='explicit').count()
    num_incipits = Prose.objects.filter(type='incipit').count()
    num_subjects = Prose.objects.filter(type='subject').count()
    num_titles = Prose.objects.filter(type='title').count()
    return render(request, 'proses/index.html', {'num_explicits': num_explicits,
                                                 'num_incipits': num_incipits,
                                                 'num_subjects': num_subjects,
                                                 'num_titles': num_titles,
                                                 "index_home":"active"})


class DetailView(generic.DetailView):
    model = Prose
    template_name = 'proses/detail.html'


class UploadFileForm(forms.Form):
    file = forms.FileField()
    type = forms.CharField(label='Type of file', widget=forms.Select(choices=UPLOAD_TYPES))


def prose_table(request):
    name = request.resolver_match.url_name
    breadcrumbs = {}
    breadcrumbs[0] = dict(name=VIEW_TYPES[name], url=request.path)

    if 'query' in request.GET:
        search_val = request.GET['query']
    else:
        search_val = None

    if search_val and len(search_val)>0:
        response = requests.get('https://tekstlab.uio.no/imep_search', params={'query': search_val, 'type': name})
        fuzzy_search_ids = response.text.split(',')
        fuzzy_search_rankings = dict(map(lambda args: (args[1], args[0]), enumerate(fuzzy_search_ids)))
        exact_matches = ProseBook.objects.filter(prose__type=name, prose__prose_text__iregex=search_val.strip())
        exact_match_ids = set(map(lambda pb: pb.prose_id, exact_matches))
        pbs = list(ProseBook.objects.filter(Q(prose__type=name, prose__prose_text__iregex=search_val.strip()) | Q(prose__type=name, prose_id__in=fuzzy_search_ids)))
        pbs.sort(key = lambda pb: pb.prose_id in exact_match_ids and -1 or fuzzy_search_rankings.get(str(pb.prose_id), -1))

        breadcrumbs[1] = dict(name='Query: ' + search_val, url=request.path + '?query=' + search_val)
    else:
        pbs = list(ProseBook.objects.filter(prose__type=name))
        search_val = None

    if name == 'incipit':
        table = IncipitsTable(pbs)
    elif name == 'explicit':
        table = ExcipitsTable(pbs)
    elif name == 'title':
        table = TitlesTable(pbs)
    elif name == 'subject':
        table = GeneralIndexTable(pbs)

    RequestConfig(request, paginate={'per_page': 25}).configure(table)
    return render(request, 'proses/mytable.html',
                  {'site_name': VIEW_TYPES[name],
                   'table_name':
                       '' if search_val is None else
                       'Found ' + str(len(pbs)) + ' ' + VIEW_TYPES[name] + ' containing: ' + search_val,
                   'table': table,
                   'breadcrumbs': breadcrumbs,
                   'query_text': "" if search_val is None else search_val,
                   name : "active"}
                    )


def search(request):
    if 'query' in request.GET:
        message = 'You searched for: %r' % request.GET['query']
    else:
        message = 'Please enter text to search for.'
    return HttpResponse(message)


def volume_index(request):
    template_name = 'proses/volume_index.html'
    return render(request, template_name)


def import_sheet(request):
    if request.method == "POST":

        form = UploadFileForm(request.POST,
                              request.FILES)
        if form.is_valid():
            upload_type = form.cleaned_data['type']
            file_handle = request.FILES['file']
            import_file_content(file_handle.name, file_handle.file.read(), upload_type)
            return HttpResponse("OK")
        else:
            return HttpResponseBadRequest()
    else:
        form = UploadFileForm()
    return render(
        request,
        'proses/upload_form.html',
        {'form': form})

app/templates/proses/base/base.html
{% load static %}
{% block site_name %}{{ site_name }}{% endblock %}
{% block head_title %}CDH Lab | Index of Middle English Proses{% endblock %}
{% block head_author %}{% endblock %}
{% block head_description %}{% endblock %}
{% static 'images/cdh/cdh-logo.png' %}
{% block campl_tabs_header %}{% endblock %}
{% block local_footer %}{% endblock %}
{% block all_breadcrumbs %}
    <div class="campl-breadcrumb" id="breadcrumb">
        <ul class="campl-unstyled-list campl-horizontal-navigation clearfix">
                                        <li class='first-child'>
                                    <a href="#" class="campl-home ir">Home</a>
                                </li>
            {# My app name #}
            {% block static_breadcrumbs %}

                <li >
                    <a href="/proses">IMEP</a>
                </li>

            {% endblock %}
            {% comment %}
                                        Application-specific breadcrumbs are handled by this little loop.
                                        Pass a dictionary of any additional breadcrumbs as "breadcrumbs"
                                        like:
                                            breadcrumbs = {}
                                            breadcrumbs[0] = dict(name='Page of my cool app', url='http://my.cool.app/page/')
                                            breadcrumbs[1] = dict(name='Subpage of my cool app', url='http://my.cool.app/page/subthingy/')
                                            ...
                                            return render_to_response('campl.html', {'breadcrumbs':breadcrumbs, ...})
                                    {% endcomment %}
            {% for index, breadcrumb in breadcrumbs.items %}
                <li>
                    <a href="{{ breadcrumb.url }}">{{ breadcrumb.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

app/templates/proses/base/prose_template.html
<!-- Common to all Proses views -->
{% extends "proses/base/template.html" %}
{% load static %}
{% block styles %}
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'proses/proses_1.css' %}">
    <link rel="stylesheet" href="{% static 'proses/mbr-additional.css' %}">
    <link rel="stylesheet" href="{% static 'proses/card-pin.css' %}"/>
    <link rel="stylesheet" href="{% static 'proses/style.css' %}"/>
{% endblock %}

{% block head_title %}IMEP - Index of Middle English Prose{% endblock %}
{% block template_navbar %}
    <nav class="col-lg-12 navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
<!--        <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="{% url 'proses:index' %}">
                         <img src="{% static 'images/book-icon.png' %}" alt="IMEP" style="height: 3.8rem;">
                    </a>
                </span>
        </div>
-->
        <a class="navbar-brand" href="{% url 'proses:index' %}">IMEP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {{ index_home }}">
                    <a class="nav-link" href="{% url 'proses:index' %}">Home <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {{ incipit }}"><a class="nav-link" href="{% url 'proses:incipit' %}">Incipits</a>
                </li>
                <li class="nav-item {{ explicit }}"><a class="nav-link" href="{% url 'proses:explicit' %}">Reverse Explicits</a>
                </li>

                <li class="nav-item {{ title }}"><a class="nav-link" href="{% url 'proses:title' %}">Titles and Rubrics</a></li>
                <li class="nav-item {{ subject }}"><a class="nav-link" href="{% url 'proses:subject' %}">General Index</a>
                </li>
<!--                <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
                                                 role="button"
                                                 data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Admin</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/admin">Control</a>
                    </div>
                </li>
                -->
            </ul>
            {% block search_bar %}
                <!-- override this for your own search bar -->
                <form action="{% block search_action %}#{% endblock %}" method="get">
                    <fieldset>
                        <div class="campl-control-group">
                            <div class="campl-search-input">
                                <input type="text" id="query" name="query" size="40" value="{{ query_text }}"
                                       style="height: 39px;vertical-align: center"/>

                                <input class="campl-search-submit " type="image"
                                       src="{% static 'images/btn-search-inpage.png' %}"
                                       style="width:39px;height:39px;vertical-align: center"/>
                            </div>
                        </div>
                    </fieldset>
                </form>
            {% endblock %}
        </div>
    </nav>
{% endblock %}

{% block footer %}
    <section id="footer">
        <div class="row bg-dark text-white">
            <div class="col-lg-2">
                <div class="media-wrap">
                    <a href="https://www.cdh.cam.ac.uk">
                        <img src="{% static 'images/cdh-lab.png' %}" alt="CDH-lab" width="178">
                    </a>
                </div>
            </div>
            <div class="col-lg-7 text-center">
                <div class="footer-text">
                    <p style="padding-top: 10px;">A CDH Lab project built and supported by <br>Cambridge University Library Development team</p>
                </div>
                <!--
                <a class="text-primary" href="https://www.lib.cam.ac.uk">Cambridge University Libraries</a> &middot;
                <a class="text-primary" href="https://www.cam.ac.uk">University of Cambridge</a>
                -->
            </div>
            <div class="col-lg-2">
                <div class="media-wrap" style="alignment: right;">
                    <a href="https://www.lib.cam.ac.uk">
                        <img src="{% static 'images/ucamlib-logo.png' %}" alt="Cambridge University Libraries" width="178" style="padding-top: 10px;">
                    </a>
                </div>
            </div>

        </div>
    </section>
{% endblock %}

app/templates/proses/base/template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block cdh_block_head %}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block head_title %}A CDHLab web site{% endblock %}</title>

        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
              crossorigin="anonymous">
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
        <link rel="stylesheet" href="{% static 'proses/proses_1.css' %}">
        <link rel="stylesheet" href="{% static 'proses/mbr-additional.css' %}">
        <link rel="stylesheet" href="{% static 'proses/card-pin.css' %}"/>
        {% block styles %}
        {% endblock %}
    {% endblock %}
</head>
<body>
<div class="container">
    {% block template_head %}
    {% endblock %}
    {% block template_navbar %}
        <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark"><a class="navbar-brand" href="#">IMEP</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                    class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active"><a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="#">Link</a></li>
                    <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"
                                                     role="button"
                                                     data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown"><a class="dropdown-item"
                                                                                       href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a></div>
                    </li>
                    <li class="nav-item"><a class="nav-link disabled" href="#">Disabled</a></li>
                </ul>

                {% block search_bar %}
                    <!-- override this for your own search bar -->
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                {% endblock %}
            </div>
        </nav>
    {% endblock %}


    {% block head_subtitle %}
    {% endblock %}

    {% block content_body %}
    {% endblock %}

    {% block footer %}
        <div class="row">
            <div class="text-center col-lg-6 offset-lg-3">
                <h4>Footer </h4>
            </div>
        </div>
    {% endblock %}
</div>  <!-- container -->

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>


<!-- Include all compiled plugins (below), or include individual files as needed -->
<!--
<script src="js/jquery-3.2.1.min.js"></script>
<script src="js/popper.min.js"></script> 
<script src="js/bootstrap-4.0.0.js"></script>
-->
</body>
</html>